-- TABLE EMPLOYEES

-- CREATE TABLE EMPLOYEES
CREATE TABLE EMPLOYEES
(
  FIRSTNAME VARCHAR2(20) NOT NULL,
  LASTNAME VARCHAR2(20) NOT NULL,
  EMAILADDRESS VARCHAR2(20) NOT NULL,
  BSNNUMBER NUMBER(9) NOT NULL,
  DATEOFBIRTH DATE NOT NULL
);

